#!/usr/bin/env python3
"""Ablation sweep driver for cilkprace/leb8-single.

For each configuration it rewrites cheetah's cilkprace_ablation_config.h,
rebuilds the cilkprace runtime and the benchmarks, then runs each benchmark a
number of times at each worker count and records the benchmark's own reported
time (min over -i iterations, printed on stdout).

The config header is restored on exit, including on Ctrl-C.

Example:
    tools/ablate.py --trials 3 --iters 3 --workers 1,10 \\
                    --out ablation-results/sweep.csv
"""

import argparse
import atexit
import csv
import os
import re
import shutil
import signal
import statistics
import subprocess
import sys
import time
from pathlib import Path

# Every knob in cilkprace_ablation.h. "off" means the optimization is removed.
KNOBS = [
    "READ_WIDEN_FASTPATH",
    "READ_SLOW_IDENTICAL",
    "WRITE_FASTPATH",
    "SEQLOCK",
    "CACHE_ALIGN",
    "RBW_FILTER",
    "GRANULE_UNROLL",
    "LABEL_CMP_FASTPATH",
    "BRANCH_HINTS",
]

# Disabling the seqlock is only sound with a single worker.
SINGLE_WORKER_ONLY = {"SEQLOCK"}

BENCHMARKS = [
    "cholesky", "cilksort", "fib", "lu", "matmul",
    "nqueens", "qsort", "rectmul", "rectmulred", "strassen",
]

_FLOAT_LINE = re.compile(r"^\s*(\d+\.\d+)\s*$")

HEADER_TMPL = """#ifndef _CILKPRACE_ABLATION_CONFIG_H
#define _CILKPRACE_ABLATION_CONFIG_H

// Generated by tools/ablate.py -- do not edit by hand while a sweep is running.
// Config: {name}
{defines}
#endif /* _CILKPRACE_ABLATION_CONFIG_H */
"""


class ConfigHeader:
    """Rewrites the ablation config header, restoring the original on exit."""

    def __init__(self, path):
        self.path = Path(path)
        self.original = self.path.read_text()
        self._restored = False
        atexit.register(self.restore)
        for sig in (signal.SIGINT, signal.SIGTERM):
            signal.signal(sig, self._on_signal)

    def _on_signal(self, signum, frame):
        self.restore()
        sys.exit(128 + signum)

    def write(self, name, disabled):
        defines = "".join(
            f"#define CILKPRACE_ABL_{k} 0\n" for k in disabled
        )
        self.path.write_text(HEADER_TMPL.format(name=name, defines=defines))

    def restore(self):
        if not self._restored:
            self.path.write_text(self.original)
            self._restored = True


def run(cmd, cwd, what):
    proc = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    if proc.returncode != 0:
        sys.stderr.write(f"\n{what} failed:\n{proc.stdout[-4000:]}{proc.stderr[-4000:]}\n")
        raise SystemExit(1)
    return proc


def build(args, jobs):
    run(["make", "cilkprace", f"-j{jobs}"], args.runtimes_dir, "runtime build")
    targets = [f"{b}.cilkprace" for b in args.benchmarks]
    run(["make", *targets, f"-j{jobs}"], args.bench_build, "benchmark build")


def time_one(exe, workers, iters, timeout):
    """Run one benchmark process. Returns (seconds, note)."""
    env = dict(os.environ, CILK_NWORKERS=str(workers))
    try:
        proc = subprocess.run([str(exe), "-i", str(iters)], env=env,
                              capture_output=True, text=True, timeout=timeout)
    except subprocess.TimeoutExpired:
        return None, "timeout"
    # A reported race means the tool aborted partway -- the time is meaningless.
    if "RACE" in proc.stderr:
        return None, "race-reported"
    for line in reversed(proc.stdout.splitlines()):
        m = _FLOAT_LINE.match(line)
        if m:
            return float(m.group(1)), ""
    return None, f"no-time-output(rc={proc.returncode})"


def configs_for(spec, base=(), skip=()):
    """Yield (name, [disabled knobs]) pairs.

    `base` is disabled in every config including the baseline, which is how a
    greedy hill-climb measures each remaining knob against the best config found
    so far rather than against the all-on build. `skip` drops knobs from the
    generated one-at-a-time set (e.g. SEQLOCK, which cannot be adopted).
    """
    base = list(base)
    candidates = [k for k in KNOBS if k not in base and k not in skip]
    out = [("baseline", list(base))]
    if spec == "one-at-a-time":
        out += [(f"no-{k}", base + [k]) for k in candidates]
    elif spec == "all-off":
        out.append(("all-off", list(KNOBS)))
    elif spec == "full":
        out += [(f"no-{k}", base + [k]) for k in candidates]
        out.append(("all-off", list(KNOBS)))
    else:
        for name in spec.split(","):
            name = name.strip()
            if name == "baseline":
                continue
            knobs = [k.strip() for k in name[3:].split("+")] if name.startswith("no-") \
                else [k.strip() for k in name.split("+")]
            unknown = [k for k in knobs if k not in KNOBS]
            if unknown:
                raise SystemExit(f"unknown knob(s): {', '.join(unknown)}")
            merged = base + [k for k in knobs if k not in base]
            out.append((name, merged))
    return out


def main():
    here = Path(__file__).resolve().parent
    examples = here.parent
    project = examples.parents[2]  # .../opencilk-project

    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--config-header",
                   default=str(project / "cheetah/include/cilk/cilkprace_ablation_config.h"))
    p.add_argument("--runtimes-dir",
                   default=str(project / "build/runtimes/runtimes-bins"))
    p.add_argument("--bench-build", default=str(examples / "build-ablate"))
    p.add_argument("--configs", default="full",
                   help="'full' (default), 'one-at-a-time', 'all-off', or a "
                        "comma-separated list like 'no-SEQLOCK,no-CACHE_ALIGN+BRANCH_HINTS'")
    p.add_argument("--benchmarks", default=",".join(BENCHMARKS))
    p.add_argument("--workers", default="1,10",
                   help="comma-separated worker counts (default 1,10)")
    p.add_argument("--trials", type=int, default=3, help="processes per cell")
    p.add_argument("--iters", type=int, default=3, help="-i passed to each benchmark")
    p.add_argument("--timeout", type=float, default=600.0)
    p.add_argument("--jobs", type=int, default=os.cpu_count())
    p.add_argument("--out", default=str(examples / "ablation-results/sweep.csv"))
    p.add_argument("--base", default="",
                   help="knobs disabled in EVERY config, baseline included -- the "
                        "current best config in a greedy hill-climb")
    p.add_argument("--skip", default="",
                   help="knobs to leave out of the generated one-at-a-time set")
    args = p.parse_args()

    base = [k.strip() for k in args.base.split(",") if k.strip()]
    skip = [k.strip() for k in args.skip.split(",") if k.strip()]
    for k in base + skip:
        if k not in KNOBS:
            raise SystemExit(f"unknown knob: {k}")

    args.benchmarks = [b.strip() for b in args.benchmarks.split(",") if b.strip()]
    worker_counts = [int(w) for w in args.workers.split(",")]
    configs = configs_for(args.configs, base, skip)

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    for d in (args.runtimes_dir, args.bench_build):
        if not Path(d).is_dir():
            raise SystemExit(f"not a directory: {d}")

    header = ConfigHeader(args.config_header)

    n_cells = len(configs) * len(args.benchmarks) * len(worker_counts)
    print(f"{len(configs)} configs x {len(args.benchmarks)} benchmarks x "
          f"{len(worker_counts)} worker counts x {args.trials} trials "
          f"= {n_cells * args.trials} runs")
    if base:
        print(f"baseline already has disabled: {', '.join(base)}")
    print(f"writing {out_path}\n")

    started = time.time()
    with out_path.open("w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["config", "disabled", "benchmark", "workers", "trial",
                    "seconds", "note"])

        for ci, (name, disabled) in enumerate(configs, 1):
            print(f"[{ci}/{len(configs)}] {name}: building...", flush=True)
            header.write(name, disabled)
            build(args, args.jobs)

            for workers in worker_counts:
                skipped = [k for k in disabled if k in SINGLE_WORKER_ONLY]
                if workers > 1 and skipped:
                    print(f"    workers={workers}: skipped "
                          f"({'/'.join(skipped)} is unsound with >1 worker)")
                    for b in args.benchmarks:
                        w.writerow([name, "+".join(disabled), b, workers, 0, "",
                                    "skipped-unsound-multithreaded"])
                    continue

                for b in args.benchmarks:
                    exe = Path(args.bench_build) / f"{b}.cilkprace"
                    times, notes = [], set()
                    for t in range(args.trials):
                        secs, note = time_one(exe, workers, args.iters, args.timeout)
                        w.writerow([name, "+".join(disabled), b, workers, t,
                                    "" if secs is None else f"{secs:.6f}", note])
                        if secs is not None:
                            times.append(secs)
                        elif note:
                            notes.add(note)
                    fh.flush()
                    if times:
                        med = statistics.median(times)
                        spread = (max(times) - min(times)) / med * 100 if med else 0
                        extra = f"  [{'/'.join(sorted(notes))}]" if notes else ""
                        print(f"    w={workers:<3} {b:<12} {med:7.3f}s "
                              f"(+-{spread:4.1f}%){extra}")
                    else:
                        print(f"    w={workers:<3} {b:<12} FAILED "
                              f"[{'/'.join(sorted(notes))}]")

    header.restore()
    mins = (time.time() - started) / 60
    print(f"\ndone in {mins:.1f} min -> {out_path}")
    print("config header restored")


if __name__ == "__main__":
    main()
